version: "3.8"

services:
  my-api-db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapi
    ports:
      - 3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  my-api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      my-api-db:
        condition: service_healthy
